### ISSUE TITLE
Error while installing pip packages

### ISSUE THREAD

**Issue by rishi1111** [nitinraturi/python_flask_webpush_notification#1]
Solidwebpush package is not mentioned in req.txt.

ERROR: pywebpush 1.10.0 has requirement http-ece>=1.1.0, but you'll have http-ece 0.7.0 which is incompatible.
ERROR: pywebpush 1.10.0 has requirement py-vapid>=1.5.0, but you'll have py-vapid 0.7.1 which is incompatible.
ERROR: pywebpush 1.10.0 has requirement requests>=2.21.0, but you'll have requests 2.20.0 which is incompatible.

I get this error while installing it via pip.

**Comment by nitinraturi** [comment]
@rishi1111
Thanks for letting me know, I will update this repository soon and let you know via comments.

I have updated the repository and its working fine now; you can clone again. Thanks
