### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by alexanderbeloiu** [nitinraturi/python_flask_webpush_notification#2]
It says push not supported on google chrome and safari on ios.

**Comment by nitinraturi** [comment]
Hello @Alexander-69, 
It should work as I have tested on Chrome but not on safari.
1. Your chrome and safari should be updated to the latest version.
2. You should be running your application either on localhost or https.

Article help: https://raturi.in/blog/webpush-notification-using-python-and-flask/
Video help: https://youtu.be/yvHvPHI4U7Q
