### ISSUE TITLE
DOM exception: Service Worker Error DOMException: "The operation is insecure."

### ISSUE THREAD

**Issue by mohesk** [nitinraturi/python_flask_webpush_notification#3]
![image](https://user-images.githubusercontent.com/12582958/88200242-d1041b00-cc3d-11ea-98cd-fd8083b955e8.png)

**Comment by nitinraturi** [comment]
@mohesk Please use the localhost instead of IP. Chrome does not allow IP. It only allows localhost or https. Open your browser at localhost:8887/
